######################################################################
# Automatically generated by qmake (3.0) So Okt 11 00:22:43 2015
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += . ../blitz

# for filters in souretree (visual studio)
CONFIG -= flat
QT += core gui widgets 

include(../blitz.pri)
INCLUDEPATH += ../ffd_filter

# Input
HEADERS += mainwindow.h scaledialog.h ../ffd_filter/ImageFilters.h
SOURCES += main.cpp mainwindow.cpp scaledialog.cpp ../ffd_filter/ImageFilters.cpp
CONFIG(release, debug|release) {
   LIBS += -lblitz
}
CONFIG(debug, debug|release) {
   LIBS += -lblitzd
}

