Exiv2: Exiv2::Rw2Image Class Reference
Exiv2::Rw2Image Class Reference
Class to access raw Panasonic RW2 images. Exif metadata is supported directly, IPTC and XMP are read from the Exif data, if present.
#include <rw2image.hpp>
Public Member Functions
Creators
Rw2Image (BasicIo::UniquePtr io)
Constructor to open an existing RW2 image. Since the constructor can not return a result, callers should check the good() method after object construction to determine success or failure.
Manipulators
void printStructure (std::ostream &out, PrintStructureOption option, int depth) override
Print out the structure of image file.
void readMetadata () override
Read all metadata supported by a specific image format from the image. Before this method is called, the image metadata will be cleared.
void writeMetadata () override
Todo: Write metadata back to the image. This method is not yet implemented. Calling it will throw an Error(kerWritingImageFormatUnsupported).
void setExifData (const ExifData &exifData) override
Todo: Not supported yet, requires writeMetadata(). Calling this function will throw an Error(kerInvalidSettingForImage).
void setIptcData (const IptcData &iptcData) override
Todo: Not supported yet, requires writeMetadata(). Calling this function will throw an Error(kerInvalidSettingForImage).
void setComment (const std::string &comment) override
Not supported. RW2 format does not contain a comment. Calling this function will throw an Error(kerInvalidSettingForImage).
Accessors
std::string mimeType () const override
Return the MIME type of the image.
int pixelWidth () const override
Return the pixel width of the image.
int pixelHeight () const override
Return the pixel height of the image.
NOT implemented
Rw2Image (const Rw2Image &rhs)=delete
Copy constructor.
Rw2Image & operator= (const Rw2Image &rhs)=delete
Assignment operator.
Public Member Functions inherited from Exiv2::Image
Image (int imageType, uint16_t supportedMetadata, BasicIo::UniquePtr io)
Constructor taking the image type, a bitmap of the supported metadata types and an auto-pointer that owns an IO instance. See subclass constructor doc.
virtual ~Image ()=default
Virtual Destructor.
ByteOrder byteOrder () const
Return the byte order in which the Exif metadata of the image is encoded. Initially, it is not set (invalidByteOrder).
bool good () const
Check if the Image instance is valid. Use after object construction.
virtual const ExifData & exifData () const
Returns an ExifData instance containing currently buffered Exif data.
virtual const IptcData & iptcData () const
Returns an IptcData instance containing currently buffered IPTC data.
virtual const XmpData & xmpData () const
Returns an XmpData instance containing currently buffered XMP data.
virtual std::string comment () const
Return a copy of the image comment. May be an empty string.
virtual const std::string & xmpPacket () const
Return the raw XMP packet as a string.
virtual BasicIo & io () const
Return a reference to the BasicIo instance being used for Io.
AccessMode checkMode (MetadataId metadataId) const
Returns the access mode, i.e., the metadata functions, which this image supports for the metadata type metadataId.
bool supportsMetadata (MetadataId metadataId) const
Check if image supports a particular type of metadata. This method is deprecated. Use checkMode() instead.
bool writeXmpFromPacket () const
Return the flag indicating the source when writing XMP metadata.
const NativePreviewList & nativePreviews () const
Return list of native previews. This is meant to be used only by the PreviewManager.
void setTypeSupported (int imageType, uint16_t supportedMetadata)
set type support for this image format
int imageType () const
set type support for this image format
Image (const Image &rhs)=delete
Copy constructor.
Image & operator= (const Image &rhs)=delete
Assignment operator.
virtual void clearExifData ()
Erase any buffered Exif data. Exif data is not removed from the actual image until the writeMetadata() method is called.
virtual void clearIptcData ()
Erase any buffered IPTC data. IPTC data is not removed from the actual image until the writeMetadata() method is called.
virtual void setXmpPacket (const std::string &xmpPacket)
Assign a raw XMP packet. The new XMP packet is not written to the image until the writeMetadata() method is called.
virtual void clearXmpPacket ()
Erase the buffered XMP packet. XMP data is not removed from the actual image until the writeMetadata() method is called.
virtual void setXmpData (const XmpData &xmpData)
Assign new XMP data. The new XMP data is not written to the image until the writeMetadata() method is called.
virtual void clearXmpData ()
Erase any buffered XMP data. XMP data is not removed from the actual image until the writeMetadata() method is called.
virtual void clearComment ()
Erase any buffered comment. Comment is not removed from the actual image until the writeMetadata() method is called.
virtual void setIccProfile (DataBuf &&iccProfile, bool bTestValid=true)
Set the image iccProfile. The new profile is not written to the image until the writeMetadata() method is called.
virtual void clearIccProfile ()
Erase iccProfile. the profile is not removed from the actual image until the writeMetadata() method is called.
virtual bool iccProfileDefined ()
Returns the status of the ICC profile in the image instance.
virtual const DataBuf & iccProfile () const
return iccProfile
virtual void setMetadata (const Image &image)
Copy all existing metadata from source Image. The data is copied into internal buffers and is not written to the image until the writeMetadata() method is called.
virtual void clearMetadata ()
Erase all buffered metadata. Metadata is not removed from the actual image until the writeMetadata() method is called.
virtual ExifData & exifData ()
Returns an ExifData instance containing currently buffered Exif data.
virtual IptcData & iptcData ()
Returns an IptcData instance containing currently buffered IPTC data.
virtual XmpData & xmpData ()
Returns an XmpData instance containing currently buffered XMP data.
virtual std::string & xmpPacket ()
Return a modifiable reference to the raw XMP packet.
void writeXmpFromPacket (bool flag)
Determine the source when writing XMP.
void setByteOrder (ByteOrder byteOrder)
Set the byte order to encode the Exif metadata in.
void printTiffStructure (BasicIo &io, std::ostream &out, PrintStructureOption option, int depth, size_t offset=0)
Print out the structure of image file.
void printIFDStructure (BasicIo &io, std::ostream &out, Exiv2::PrintStructureOption option, uint32_t start, bool bSwap, char c, int depth)
Print out the structure of a TIFF IFD.
Additional Inherited Members
Public Types inherited from Exiv2::Image
typedef std::unique_ptr< Image > UniquePtr
Image auto_ptr type.
Static Public Member Functions inherited from Exiv2::Image
static bool isBigEndianPlatform ()
is the host platform bigEndian
static bool isLittleEndianPlatform ()
is the host platform littleEndian
static bool isStringType (uint16_t type)
static bool isShortType (uint16_t type)
static bool isLongType (uint16_t type)
static bool isLongLongType (uint16_t type)
static bool isRationalType (uint16_t type)
static bool is2ByteType (uint16_t type)
static bool is4ByteType (uint16_t type)
static bool is8ByteType (uint16_t type)
static bool isPrintXMP (uint16_t type, Exiv2::PrintStructureOption option)
static bool isPrintICC (uint16_t type, Exiv2::PrintStructureOption option)
static uint64_t byteSwap (uint64_t value, bool bSwap)
static uint32_t byteSwap (uint32_t value, bool bSwap)
static uint16_t byteSwap (uint16_t value, bool bSwap)
static uint16_t byteSwap2 (const DataBuf &buf, size_t offset, bool bSwap)
static uint32_t byteSwap4 (const DataBuf &buf, size_t offset, bool bSwap)
static uint64_t byteSwap8 (const DataBuf &buf, size_t offset, bool bSwap)
Protected Member Functions inherited from Exiv2::Image
const std::string & tagName (uint16_t tag)
Return tag name for given tag id.
Static Protected Member Functions inherited from Exiv2::Image
static const char * typeName (uint16_t tag)
Return tag type for given tag id.
Protected Attributes inherited from Exiv2::Image
BasicIo::UniquePtr io_
Image data IO pointer.
ExifData exifData_
Exif data container.
IptcData iptcData_
IPTC data container.
XmpData xmpData_
XMP data container.
DataBuf iccProfile_
ICC buffer (binary data)
std::string comment_
User comment.
std::string xmpPacket_
XMP packet.
int pixelWidth_
image pixel width
int pixelHeight_
image pixel height
NativePreviewList nativePreviews_
list of native previews
Detailed Description
Class to access raw Panasonic RW2 images. Exif metadata is supported directly, IPTC and XMP are read from the Exif data, if present.
Constructor & Destructor Documentation
Rw2Image()
Exiv2::Rw2Image::Rw2Image (BasicIo::UniquePtr io) explicit
Constructor to open an existing RW2 image. Since the constructor can not return a result, callers should check the good() method after object construction to determine success or failure.
Parameters
io An auto-pointer that owns a BasicIo instance used for reading and writing image metadata. Important: The constructor takes ownership of the passed in BasicIo instance through the auto-pointer. Callers should not continue to use the BasicIo instance after it is passed to this method. Use the Image::io() method to get a temporary reference.
Member Function Documentation
mimeType()
std::string Exiv2::Rw2Image::mimeType () const override virtual
Return the MIME type of the image.
Note
For each supported image format, the library knows only one MIME type. This may not be the most specific MIME type for that format. In particular, several RAW formats are variants of the TIFF format with the same magic as TIFF itself. Class TiffImage handles most of them and thus they all have MIME type "image/tiff", although a more specific MIME type may exist (e.g., "image/x-nikon-nef").
Implements Exiv2::Image.
pixelHeight()
int Exiv2::Rw2Image::pixelHeight () const override virtual
Return the pixel height of the image.
Reimplemented from Exiv2::Image.
References Exiv2::ExifData::end(), Exiv2::Image::exifData_, and Exiv2::ExifData::findKey().
pixelWidth()
int Exiv2::Rw2Image::pixelWidth () const override virtual
Return the pixel width of the image.
Reimplemented from Exiv2::Image.
References Exiv2::ExifData::end(), Exiv2::Image::exifData_, and Exiv2::ExifData::findKey().
printStructure()
void Exiv2::Rw2Image::printStructure (std::ostream & out, PrintStructureOption option, int depth) override virtual
Print out the structure of image file.
Exceptions
Error if reading of the file fails or the image data is not valid (does not look like data of the specific image type).
Warning
This function is not thread safe and intended for exiv2 -pS for debugging.
You may need to put the stream into binary mode (see src/actions.cpp)
Reimplemented from Exiv2::Image.
References Exiv2::Image::imageType(), Exiv2::Image::io(), Exiv2::Image::io_, Exiv2::isRw2Type(), Exiv2::ImageType::none, Exiv2::Image::printTiffStructure(), and Exiv2::strError().
readMetadata()
void Exiv2::Rw2Image::readMetadata () override virtual
Read all metadata supported by a specific image format from the image. Before this method is called, the image metadata will be cleared.
This method returns success even if no metadata is found in the image. Callers must therefore check the size of individual metadata types before accessing the data.
Exceptions
Error if opening or reading of the file fails or the image data is not valid (does not look like data of the specific image type).
Implements Exiv2::Image.
References Exiv2::ExifData::add(), Exiv2::Image::clearMetadata(), Exiv2::Rw2Parser::decode(), Exiv2::ExifData::empty(), Exiv2::ExifData::end(), Exiv2::ExifData::erase(), Exiv2::Image::exifData(), Exiv2::Image::exifData_, EXV_WARNING, Exiv2::ExifData::findKey(), Exiv2::PreviewManager::getPreviewImage(), Exiv2::PreviewManager::getPreviewProperties(), Exiv2::Image::io_, Exiv2::Image::iptcData_, Exiv2::isRw2Type(), Exiv2::ImageFactory::open(), Exiv2::PreviewImage::pData(), Exiv2::Image::setByteOrder(), Exiv2::PreviewImage::size(), Exiv2::strError(), and Exiv2::Image::xmpData_.
setComment()
void Exiv2::Rw2Image::setComment (const std::string & comment) override virtual
Not supported. RW2 format does not contain a comment. Calling this function will throw an Error(kerInvalidSettingForImage).
Reimplemented from Exiv2::Image.
setExifData()
void Exiv2::Rw2Image::setExifData (const ExifData & exifData) override virtual
Todo: Not supported yet, requires writeMetadata(). Calling this function will throw an Error(kerInvalidSettingForImage).
Reimplemented from Exiv2::Image.
setIptcData()
void Exiv2::Rw2Image::setIptcData (const IptcData & iptcData) override virtual
Todo: Not supported yet, requires writeMetadata(). Calling this function will throw an Error(kerInvalidSettingForImage).
Reimplemented from Exiv2::Image.
writeMetadata()
void Exiv2::Rw2Image::writeMetadata () override virtual
Todo: Write metadata back to the image. This method is not yet implemented. Calling it will throw an Error(kerWritingImageFormatUnsupported).
Implements Exiv2::Image.
The documentation for this class was generated from the following files:
rw2image.hpp
rw2image.cpp