Exiv2: Exiv2::Exifdatum Class Reference
Exiv2::Exifdatum Class Reference
An Exif metadatum, consisting of an ExifKey and a Value and methods to manipulate these.
#include <exif.hpp>
Public Member Functions
Creators
Exifdatum (const ExifKey &key, const Value *pValue=nullptr)
Constructor for new tags created by an application. The Exifdatum is created from a key / value pair. Exifdatum copies (clones) the key and value if one is provided. Alternatively, a program can create an 'empty' Exifdatum with only a key and set the value using setValue().
Exifdatum (const Exifdatum &rhs)
Copy constructor.
~Exifdatum () override=default
Destructor.
Manipulators
Exifdatum & operator= (const Exifdatum &rhs)
Assignment operator.
Exifdatum & operator= (const uint16_t &value)
Assign value to the Exifdatum. The type of the new Value is set to UShortValue.
Exifdatum & operator= (const uint32_t &value)
Assign value to the Exifdatum. The type of the new Value is set to ULongValue.
Exifdatum & operator= (const URational &value)
Assign value to the Exifdatum. The type of the new Value is set to URationalValue.
Exifdatum & operator= (const int16_t &value)
Assign value to the Exifdatum. The type of the new Value is set to ShortValue.
Exifdatum & operator= (const int32_t &value)
Assign value to the Exifdatum. The type of the new Value is set to LongValue.
Exifdatum & operator= (const Rational &value)
Assign value to the Exifdatum. The type of the new Value is set to RationalValue.
Exifdatum & operator= (const std::string &value)
Assign value to the Exifdatum. Calls setValue(const std::string&).
Exifdatum & operator= (const Value &value)
Assign value to the Exifdatum. Calls setValue(const Value*).
void setValue (const Value *pValue) override
Set the value. This method copies (clones) the value pointed to by pValue.
int setValue (const std::string &value) override
Set the value to the string value. Uses Value::read(const std::string&). If the Exifdatum does not have a Value yet, then a Value of the correct type for this Exifdatum is created. An AsciiValue is created for unknown tags. Return 0 if the value was read successfully.
int setDataArea (const byte *buf, long len)
Set the data area by copying (cloning) the buffer pointed to by buf.
Public Member Functions inherited from Exiv2::Metadatum
Metadatum ()=default
Default Constructor.
Metadatum (const Metadatum &rhs)=default
Copy constructor.
virtual ~Metadatum ()=default
Destructor.
std::string print (const ExifData *pMetadata=nullptr) const
Write the interpreted value to a string.
Friends
template<typename T >
Exifdatum & setValue (Exifdatum &, const T &)
Set the value of exifDatum to value. If the object already has a value, it is replaced. Otherwise a new ValueType<T> value is created and set to value.
Accessors
std::string key () const override
Return the key of the Exifdatum.
const char * familyName () const override
Return the name of the metadata family (which is also the first part of the key)
std::string groupName () const override
Return the name of the metadata group (which is also the second part of the key)
std::string tagName () const override
Return the name of the tag (which is also the third part of the key)
std::string tagLabel () const override
Return a label for the tag.
uint16_t tag () const override
Return the tag.
int ifdId () const
Return the IFD id as an integer. (Do not use, this is meant for library internal use.)
const char * ifdName () const
Return the name of the IFD.
int idx () const
Return the index (unique id of this key within the original IFD)
long copy (byte *buf, ByteOrder byteOrder) const override
Write value to a data buffer and return the number of bytes written.
std::ostream & write (std::ostream &os, const ExifData *pMetadata=nullptr) const override
Write the interpreted value to an output stream, return the stream.
TypeId typeId () const override
Return the type id of the value.
const char * typeName () const override
Return the name of the type.
long typeSize () const override
Return the size in bytes of one component of this type.
long count () const override
Return the number of components in the value.
long size () const override
Return the size of the value in bytes.
std::string toString () const override
Return the value as a string.
std::string toString (long n) const override
Return the n-th component of the value converted to a string. The behaviour of the method is undefined if there is no n-th component.
long toLong (long n=0) const override
Return the n-th component of the value converted to long. The return value is -1 if the value is not set and the behaviour of the method is undefined if there is no n-th component.
float toFloat (long n=0) const override
Return the n-th component of the value converted to float. The return value is -1 if the value is not set and the behaviour of the method is undefined if there is no n-th component.
Rational toRational (long n=0) const override
Return the n-th component of the value converted to Rational. The return value is -1/1 if the value is not set and the behaviour of the method is undefined if there is no n-th component.
Value::UniquePtr getValue () const override
Return an auto-pointer to a copy (clone) of the value. The caller owns this copy and the auto-poiner ensures that it will be deleted.
const Value & value () const override
Return a constant reference to the value.
long sizeDataArea () const
Return the size of the data area.
DataBuf dataArea () const
Return a copy of the data area of the value. The caller owns this copy and DataBuf ensures that it will be deleted.
Additional Inherited Members
Protected Member Functions inherited from Exiv2::Metadatum
Metadatum & operator= (const Metadatum &rhs)=default
Assignment operator. Protected so that it can only be used by subclasses but not directly.
Detailed Description
An Exif metadatum, consisting of an ExifKey and a Value and methods to manipulate these.
Examples
addmoddel.cpp.
Constructor & Destructor Documentation
Exifdatum()
Exiv2::Exifdatum::Exifdatum (const ExifKey & key, const Value * pValue = nullptr) explicit
Constructor for new tags created by an application. The Exifdatum is created from a key / value pair. Exifdatum copies (clones) the key and value if one is provided. Alternatively, a program can create an 'empty' Exifdatum with only a key and set the value using setValue().
Parameters
key ExifKey.
pValue Pointer to an Exifdatum value.
Exceptions
Error if the key cannot be parsed and converted.
References Exiv2::Value::clone().
Member Function Documentation
copy()
long Exiv2::Exifdatum::copy (byte * buf, ByteOrder byteOrder) const override virtual
Write value to a data buffer and return the number of bytes written.
The user must ensure that the buffer has enough memory. Otherwise the call results in undefined behaviour.
Parameters
buf Data buffer to write to.
byteOrder Applicable byte order (little or big endian).
Returns
Number of characters written.
Implements Exiv2::Metadatum.
count()
long Exiv2::Exifdatum::count () const override virtual
Return the number of components in the value.
Implements Exiv2::Metadatum.
Referenced by write().
dataArea()
DataBuf Exiv2::Exifdatum::dataArea () const
Return a copy of the data area of the value. The caller owns this copy and DataBuf ensures that it will be deleted.
Values may have a data area, which can contain additional information besides the actual value. This method is used to access such a data area.
Returns
A DataBuf containing a copy of the data area or an empty DataBuf if the value does not have a data area assigned or the value is not set.
familyName()
const char * Exiv2::Exifdatum::familyName () const override virtual
Return the name of the metadata family (which is also the first part of the key)
Implements Exiv2::Metadatum.
getValue()
Value::UniquePtr Exiv2::Exifdatum::getValue () const override virtual
Return an auto-pointer to a copy (clone) of the value. The caller owns this copy and the auto-poiner ensures that it will be deleted.
This method is provided for users who need full control over the value. A caller may, e.g., downcast the pointer to the appropriate subclass of Value to make use of the interface of the subclass to set or modify its contents.
Returns
An auto-pointer containing a pointer to a copy (clone) of the value, 0 if the value is not set.
Implements Exiv2::Metadatum.
Referenced by Exiv2::Internal::TiffEncoder::encodeOffsetEntry(), and Exiv2::Internal::TiffEncoder::encodeTiffEntryBase().
groupName()
std::string Exiv2::Exifdatum::groupName () const override virtual
Return the name of the metadata group (which is also the second part of the key)
Implements Exiv2::Metadatum.
key()
std::string Exiv2::Exifdatum::key () const override virtual
Return the key of the Exifdatum.
Implements Exiv2::Metadatum.
Examples
addmoddel.cpp.
setDataArea()
int Exiv2::Exifdatum::setDataArea (const byte * buf, long len)
Set the data area by copying (cloning) the buffer pointed to by buf.
Values may have a data area, which can contain additional information besides the actual value. This method is used to set such a data area.
Parameters
buf Pointer to the source data area
len Size of the data area
Returns
Return -1 if the Exifdatum does not have a value yet or the value has no data area, else 0.
Referenced by Exiv2::ExifThumb::setJpegThumbnail().
setValue() [1/2]
int Exiv2::Exifdatum::setValue (const std::string & value) override virtual
Set the value to the string value. Uses Value::read(const std::string&). If the Exifdatum does not have a Value yet, then a Value of the correct type for this Exifdatum is created. An AsciiValue is created for unknown tags. Return 0 if the value was read successfully.
Implements Exiv2::Metadatum.
References Exiv2::Value::create(), and value().
setValue() [2/2]
void Exiv2::Exifdatum::setValue (const Value * pValue) override virtual
Set the value. This method copies (clones) the value pointed to by pValue.
Implements Exiv2::Metadatum.
References Exiv2::Value::clone().
size()
long Exiv2::Exifdatum::size () const override virtual
Return the size of the value in bytes.
Implements Exiv2::Metadatum.
Referenced by Exiv2::Internal::TiffEncoder::encodeOffsetEntry(), and Exiv2::Internal::TiffEncoder::encodeTiffEntryBase().
tag()
uint16_t Exiv2::Exifdatum::tag () const override virtual
Return the tag.
Implements Exiv2::Metadatum.
Referenced by write().
tagLabel()
std::string Exiv2::Exifdatum::tagLabel () const override virtual
Return a label for the tag.
Implements Exiv2::Metadatum.
tagName()
std::string Exiv2::Exifdatum::tagName () const override virtual
Return the name of the tag (which is also the third part of the key)
Implements Exiv2::Metadatum.
toFloat()
float Exiv2::Exifdatum::toFloat (long n = 0) const override virtual
Return the n-th component of the value converted to float. The return value is -1 if the value is not set and the behaviour of the method is undefined if there is no n-th component.
Implements Exiv2::Metadatum.
toLong()
long Exiv2::Exifdatum::toLong (long n = 0) const override virtual
Return the n-th component of the value converted to long. The return value is -1 if the value is not set and the behaviour of the method is undefined if there is no n-th component.
Implements Exiv2::Metadatum.
toRational()
Rational Exiv2::Exifdatum::toRational (long n = 0) const override virtual
Return the n-th component of the value converted to Rational. The return value is -1/1 if the value is not set and the behaviour of the method is undefined if there is no n-th component.
Implements Exiv2::Metadatum.
toString() [1/2]
std::string Exiv2::Exifdatum::toString () const override virtual
Return the value as a string.
Implements Exiv2::Metadatum.
Examples
addmoddel.cpp.
toString() [2/2]
std::string Exiv2::Exifdatum::toString (long n) const override virtual
Return the n-th component of the value converted to a string. The behaviour of the method is undefined if there is no n-th component.
Implements Exiv2::Metadatum.
typeId()
TypeId Exiv2::Exifdatum::typeId () const override virtual
Return the type id of the value.
Implements Exiv2::Metadatum.
References Exiv2::invalidTypeId.
Referenced by typeName(), and typeSize().
typeName()
const char * Exiv2::Exifdatum::typeName () const override virtual
Return the name of the type.
Implements Exiv2::Metadatum.
References typeId(), and Exiv2::TypeInfo::typeName().
typeSize()
long Exiv2::Exifdatum::typeSize () const override virtual
Return the size in bytes of one component of this type.
Implements Exiv2::Metadatum.
References typeId(), and Exiv2::TypeInfo::typeSize().
value()
const Value & Exiv2::Exifdatum::value () const override virtual
Return a constant reference to the value.
This method is provided mostly for convenient and versatile output of the value which can (to some extent) be formatted through standard stream manipulators. Do not attempt to write to the value through this reference. An Error is thrown if the value is not set; as an alternative to catching it, one can use count() to check if there is any data before calling this method.
Returns
A constant reference to the value.
Exceptions
Error if the value is not set.
Implements Exiv2::Metadatum.
Examples
addmoddel.cpp.
Referenced by operator=(), setValue(), and write().
write()
std::ostream & Exiv2::Exifdatum::write (std::ostream & os, const ExifData * pMetadata = nullptr) const override virtual
Write the interpreted value to an output stream, return the stream.
The method takes an optional pointer to a metadata container. Pretty-print functions may use that to refer to other metadata as it is sometimes not sufficient to know only the value of the metadatum that should be interpreted. Thus, it is advisable to always call this method with a pointer to the metadata container if possible.
This functionality is currently only implemented for Exif tags. The pointer is ignored when used to write IPTC datasets or XMP properties.
Without the optional metadata pointer, you do not usually have to use this function; it is used for the implementation of the output operator for Metadatum, operator<<(std::ostream &os, const Metadatum &md).
See also print(), which prints the interpreted value to a string.
Implements Exiv2::Metadatum.
References Exiv2::comment, count(), ifdId(), Exiv2::TagInfo::printFct_, Exiv2::Internal::printValue(), tag(), Exiv2::Internal::tagInfo(), Exiv2::Value::toString(), Exiv2::TagInfo::typeId_, and value().
Friends And Related Function Documentation
setValue
template<typename T > Exifdatum & setValue (Exiv2::Exifdatum & exifDatum, const T & value) friend
Set the value of exifDatum to value. If the object already has a value, it is replaced. Otherwise a new ValueType<T> value is created and set to value.
This is a helper function, called from Exifdatum members. It is meant to be used with T = (u)int16_t, (u)int32_t or (U)Rational. Do not use directly.
Examples
addmoddel.cpp.
Referenced by Exiv2::Converter::cnvXmpValue(), and operator=().
The documentation for this class was generated from the following files:
exif.hpp
exif.cpp