Exiv2: Exiv2::Internal::PanasonicMnHeader Class Reference
Exiv2::Internal::PanasonicMnHeader Class Reference
Header of a Panasonic Makernote.
#include <makernote_int.hpp>
Public Member Functions
Creators
PanasonicMnHeader ()
Default constructor.
~PanasonicMnHeader () override=default
Virtual destructor.
Manipulators
bool read (const byte *pData, uint32_t size, ByteOrder byteOrder) override
Read the header from a data buffer, return true if ok.
Public Member Functions inherited from Exiv2::Internal::MnHeader
virtual ~MnHeader ()=default
Virtual destructor.
virtual void setByteOrder (ByteOrder byteOrder)
Set the byte order for the makernote.
virtual ByteOrder byteOrder () const
Return the byte order for the makernote. If the return value is invalidByteOrder, this means that the byte order of the the image should be used for the makernote.
virtual uint32_t baseOffset (uint32_t mnOffset) const
Return the base offset for the makernote IFD entries relative to the start of the TIFF header. mnOffset is the offset to the makernote from the start of the TIFF header.
Accessors
uint32_t size () const override
Return the size of the header (in bytes).
uint32_t write (IoWrapper &ioWrapper, ByteOrder byteOrder) const override
Write the header to a data buffer, return the number of bytes written.
uint32_t ifdOffset () const override
Return the offset to the start of the Makernote IFD from the start of the Makernote (= the start of the header).
static uint32_t sizeOfSignature ()
Return the size of the makernote header signature.
Detailed Description
Header of a Panasonic Makernote.
Member Function Documentation
ifdOffset()
uint32_t Exiv2::Internal::PanasonicMnHeader::ifdOffset () const override virtual
Return the offset to the start of the Makernote IFD from the start of the Makernote (= the start of the header).
Reimplemented from Exiv2::Internal::MnHeader.
read()
bool Exiv2::Internal::PanasonicMnHeader::read (const byte * pData, uint32_t size, ByteOrder byteOrder) override virtual
Read the header from a data buffer, return true if ok.
Implements Exiv2::Internal::MnHeader.
References Exiv2::DataBuf::alloc(), Exiv2::DataBuf::copyBytes(), size(), and sizeOfSignature().
Referenced by PanasonicMnHeader().
size()
uint32_t Exiv2::Internal::PanasonicMnHeader::size () const override virtual
Return the size of the header (in bytes).
Implements Exiv2::Internal::MnHeader.
References sizeOfSignature().
Referenced by read().
write()
uint32_t Exiv2::Internal::PanasonicMnHeader::write (IoWrapper & ioWrapper, ByteOrder byteOrder) const override virtual
Write the header to a data buffer, return the number of bytes written.
Implements Exiv2::Internal::MnHeader.
References sizeOfSignature(), and Exiv2::Internal::IoWrapper::write().
The documentation for this class was generated from the following files:
makernote_int.hpp
makernote_int.cpp